#[derive(Debug, PartialEq, Clone)]
pub enum Token {
    Identifier(String),
    Type(String),
    StringStart,
    StringFragment(String),
    ExprStart,
    ExprEnd,
    StringEnd,
    Character(char),
    Integer(i64),
    Float(f64),
    Boolean(bool),
    NewLine,
    Comma,
    Period,
    Colon,
    Unknown(char),
    Keyword(String),
    Operation(String),
    BlockDelimeter(String, bool),
}